from django.urls import path, include
from .views import user_top, user_mem_reg, user_pass_reset, user_profile_inf, user_good_board,\
user_item_list, user_join_fig, user_report, user_board_reg, board_inf, user_fig_reg, fig_inf,\
visit_user_inf, shop, gloval_nav, user_setting, admin_top, admin_user_inf, point, fig_req_inf,\
admin_inq, notice, admin_report, admin_inf, identification

urlpatterns = [
    ppath('F010_Top/', user_top.F010_Top, name='F010_Top'),
    path('F020_userLogin/', user_top.F020_userLogin, name='F020_userLogin'),
    path('F030_userTop/', user_top.F030_userTop, name='F030_userTop'),
    path('F040_userMemReg/', user_mem_reg.F040_userMemReg, name='F040_userMemReg'),
    path('F050_userMemRegConf/', user_mem_reg.F050_userMemRegConf, name='F050_userMemRegConf'),
    path('F060_userMemRegComp/', user_mem_reg.F060_userMemRegComp, name='F060_userMemRegComp'),
    path('F070_userPassForgot/', user_pass_reset.F070_userPassForgot, name='F070_userPassForgot'),
    path('F080_userPassResetting/', user_pass_reset.F080_userPassResetting, name='F080_userPassResetting'),
    path('F090_userPassResettingComp/', user_pass_reset.F090_userPassResettingComp, name='F090_userPassResettingComp'),
    path('F100_myProfileDet/', user_profile_inf.F100_myProfileDet, name='F100_myProfileDet'),
    path('F101_identification_app/', user_profile_inf.F101_identification_app, name='F101_identification_app'),
    path('F110_myProfileEdit/', user_profile_inf.F110_myProfileEdit, name='F110_myProfileEdit'),
    path('F120_myGoodBoardList/', user_good_board.F120_myGoodBoardList, name='F120_myGoodBoardList'),
    path('F130_myGoodBoardDet/', user_good_board.F130_myGoodBoardDet, name='F130_myGoodBoardDet'),
    path('F140_myFigmatchDet/', user_item_list.F140_myFigmatchDet, name='F140_myFigmatchDet'),
    path('F150_myBoardDet/', user_item_list.F150_myBoardDet, name='F150_myBoardDet'),
    path('F160_myBoardEdit/', user_item_list.F160_myBoardEdit, name='F160_myBoardEdit'),
    path('F170_myFigmatchEdit/', user_item_list.F170_myFigmatchEdit, name='F170_myFigmatchEdit'),
    path('F180_userPlanFigmatch/', user_join_fig.F180_userPlanFigmatch, name='F180_userPlanFigmatch'),
    path('F190_userPlanFigmatchDet/', user_join_fig.F190_userPlanFigmatchDet, name='F190_userPlanFigmatchDet'),
    path('F200_ReportForm/', user_report.F200_ReportForm, name='F200_ReportForm'),
    path('F210_ReportComp/', user_report.F210_ReportComp, name='F210_ReportComp'),
    path('F220_userBoardReg/', user_board_reg.F220_userBoardReg, name='F220_userBoardReg'),
    path('F230_userBoardRegConf/', user_board_reg.F230_userBoardRegConf, name='F230_userBoardRegConf'),
    path('F240_userBoardRegComp/', user_board_reg.F240_userBoardRegComp, name='F240_userBoardRegComp'),
    path('F250_BoardCateList/', board_inf.F250_BoardCateList, name='F250_BoardCateList'),
    path('F260_BoardSearchResult/', board_inf.F260_BoardSearchResult, name='F260_BoardSearchResult'),
    path('F270_BoardListByCate/', board_inf.F270_BoardListByCate, name='F270_BoardListByCate'),
    path('F280_BoardEdit/', board_inf.F280_BoardEdit, name='F280_BoardEdit'),
    path('F290_userFigmatchReg/', user_fig_reg.F290_userFigmatchReg, name='F290_userFigmatchReg'),
    path('F300_userFigmatchRegConf/', user_fig_reg.F300_userFigmatchRegConf, name='F300_userFigmatchRegConf'),
    path('F310_userFigmatchRegComp/', user_fig_reg.F310_userFigmatchRegComp, name='F310_userFigmatchRegComp'),
    path('F320_FigmatchList/', fig_inf.F320_FigmatchList, name='F320_FigmatchList'),
    path('F330_FigmatchSearch/', fig_inf.F330_FigmatchSearch, name='F330_FigmatchSearch'),
    path('F340_FigmatchDet/', fig_inf.F340_FigmatchDet, name='F340_FigmatchDet'),
    path('F350_FigmatchApp/', fig_inf.F350_FigmatchApp, name='F350_FigmatchApp'),
    path('F360_FigmatchAppComp/', fig_inf.F360_FigmatchAppComp, name='F360_FigmatchAppComp'),
    path('F370_visitUserProfile/', visit_user_inf.F370_visitUserProfile, name='F370_visitUserProfile'),
    
    path('F400_shopTop/', shop.F400_shopTop, name='F400_shopTop'),
    path('F410_PointShop/', shop.F410_PointShop, name='F410_PointShop'),
    path('F420_GiftShop/', shop.F420_GiftShop, name='F420_GiftShop'),
    path('F430_Privacy/', gloval_nav.F430_Privacy, name='F430_Privacy'),
    path('F440_TermsOfService/', gloval_nav.F440_TermsOfService, name='F440_TermsOfService'),
    path('F450_Inquiry/', gloval_nav.F450_Inquiry, name='F450_Inquiry'),
    path('F460_InquiryComp/', gloval_nav.F460_InquiryComp, name='F460_InquiryComp'),
    path('F470_Settings/', user_setting.F470_Settings, name='F470_Settings'),
    path('F480_passChange/', user_setting.F480_passChange, name='F480_passChange'),
    path('F490_passChangeComp/', user_setting.F490_passChangeComp, name='F490_passChangeComp'),
    path('F500_Exit/', user_setting.F500_Exit, name='F500_Exit'),
    path('F510_ExitConf/', user_setting.F510_ExitConf, name='F510_ExitConf'),
    path('F520_ExitComp/', user_setting.F520_ExitComp, name='F520_ExitComp'),
    path('F530_adminLogin/', admin_top.F530_adminLogin, name='F530_adminLogin'),
    path('F540_adminTop/', admin_top.F540_adminTop, name='F540_adminTop'),
    path('F550_adminUserList/', admin_user_inf.F550_adminUserList, name='F550_adminUserList'),
    path('F560_adminUserDet/', admin_user_inf.F560_adminUserDet, name='F560_adminUserDet'),
    path('F570_adminUserEdit/', admin_user_inf.F570_adminUserEdit, name='F570_adminUserEdit'),
    path('F580_adminBoardFigList/', admin_user_inf.F580_adminBoardFigList, name='F580_adminBoardFigList'),
    path('F590_adminBoardEdit/', admin_user_inf.F590_adminBoardEdit, name='F590_adminBoardEdit'),
    path('F600_adminFigmatchEdit/', admin_user_inf.F600_adminFigmatchEdit, name='F600_adminFigmatchEdit'),
    path('F610_awardPoint/', point.F610_awardPoint, name='F610_awardPoint'),
    path('F620_awardPointComp/', point.F620_awardPointComp, name='F620_awardPointComp'),
    path('F630_FigmatchRequest/', fig_req_inf.F630_FigmatchRequest, name='F630_FigmatchRequest'),
    path('F640_FigmatchRequestDet/', fig_req_inf.F640_FigmatchRequestDet, name='F640_FigmatchRequestDet'),
    path('F650_adminInquiryList/', admin_inq.F650_adminInquiryList, name='F650_adminInquiryList'),
    path('F660_adminInquiryDet/', admin_inq.F660_adminInquiryDet, name='F660_adminInquiryDet'),
    path('F670_Notice/', notice.F670_Notice, name='F670_Notice'),
    path('F680_adminReportList/', admin_report.F680_adminReportList, name='F680_adminReportList'),
    path('F690_adminReportDet/', admin_report.F690_adminReportDet, name='F690_adminReportDet'),
    path('F700_adminList/', admin_inf.F700_adminList, name='F700_adminList'),
    path('F710_adminDet/', admin_inf.F710_adminDet, name='F710_adminDet'),
    path('F720_adminEdit/', admin_inf.F720_adminEdit, name='F720_adminEdit'),
    path('F730_adminMemReg/', admin_inf.F730_adminMemReg, name='F730_adminMemReg'),
    path('F740_adminMemRegConf/', admin_inf.F740_adminMemRegConf, name='F740_adminMemRegConf'),
    path('F750_adminMemRegComp/', admin_inf.F750_adminMemRegComp, name='F750_adminMemRegComp'),
    path('F760_identification/', identification.F760_identification, name='F760_identification'),
    path('F770_identificationDet/', identification.F770_identificationDet, name='F770_identificationDet'),
]